# Generated by Django 4.1.7 on 2023-02-28 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dictionary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=255, unique=True)),
                ('meaning', models.CharField(max_length=255)),
                ('targetlang', models.CharField(max_length=255, unique=True)),
            ],
        ),
    ]
