# Generated by Django 4.1.7 on 2023-02-28 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Dictionary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dictionary',
            name='pronunciation',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
